# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ccda420a158249825dc6e0da6ce84fef2fbbf6b99af7e87f0aede1a031c1a3f046d20c703c1da5613ec8b229435015ca85b3e8fe11f7932cf5b3948c8ba1ba

test:
  secret_key_base: 3188fe1d68d0fb92d72491d1c52212b9f6229c37425cb76e932e2e0b1bdd54bed57543eb1eb81c68fea35b08715753e7867c08ed0944e694ae894a76c9d30d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
